@startuml
title Sistema de Moeda Estudantil - Visão Geral

actor Aluno
actor Professor
actor Empresa

participant Frontend
participant Backend
database DB
participant QUEUE
participant Email


== Login ==


Aluno -> Frontend: Faz login
activate Frontend
Professor -> Frontend: Faz login
Empresa -> Frontend: Faz login

Frontend -> Backend: Envia credenciais
activate Backend

Backend -> DB: Valida usuário
activate DB
DB --> Backend: OK
deactivate DB

Backend --> Frontend: Login confirmado
deactivate Backend
deactivate Frontend


== Envio de Moedas pelo Professor ==

Professor -> Frontend: Envia moedas para aluno
activate Frontend

Frontend -> Backend: Solicita envio
activate Backend

Backend -> DB: Atualiza saldo do aluno
activate DB
DB --> Backend: OK
deactivate DB

Backend -> Email: Notifica aluno
activate Email
Email --> Backend: Notificação enviada por Email
deactivate Email

Backend --> Frontend: Confirma envio
deactivate Backend
deactivate Frontend


== Resgate de Vantagens ==

Aluno -> Frontend: Resgata vantagem
activate Frontend

Frontend -> Backend: Solicita resgate
activate Backend

Backend -> DB: Debita moedas e registra resgate
activate DB
DB --> Backend: OK
deactivate DB

Backend -> QUEUE: Publica evento de resgate\npara envio de emails
activate QUEUE

QUEUE -> Email: Processa evento e envia cupom ao aluno
activate Email
Email --> QUEUE: Cupom enviado ao aluno
deactivate Email

QUEUE -> Email: Processa evento e notifica empresa parceira\nsobre o resgate da vantagem
activate Email
Email --> QUEUE: Notificação enviada à empresa
deactivate Email

QUEUE --> Backend: Evento encaminhado para processamento
deactivate QUEUE

Backend --> Frontend: Resgate confirmado
deactivate Backend
deactivate Frontend

== Cadastro de Vantagens ==

Empresa -> Frontend: Cadastra vantagem
activate Frontend

Frontend -> Backend: Salva vantagem
activate Backend

Backend -> DB: Persiste dados
activate DB
DB --> Backend: OK
deactivate DB

Backend --> Frontend: Vantagem cadastrada
deactivate Backend
deactivate Frontend

@enduml