@startuml
title "Envio de moedas para aluno"

actor Professor
participant "Página Web" as Frontend
participant "Backend" as Backend
database "Banco de Dados" as DB
participant Email
participant Aluno

Professor -> Frontend: Faz login
activate Frontend
Frontend -> Backend: Envia credenciais
activate Backend
Backend -> DB: Valida usuário
activate DB
DB --> Backend: OK
Backend --> Frontend: Login confirmado
deactivate DB
deactivate Backend
deactivate Frontend

Professor -> Frontend: Acessa lista de alunos
activate Frontend
Frontend -> Backend: Solicita alunos
activate Backend
Backend -> DB: Buscar alunos
activate DB
DB --> Backend: Lista de alunos
deactivate DB
Backend --> Frontend: Retorna lista
deactivate Backend
deactivate Frontend


Professor -> Frontend: Seleciona aluno + informa moedas
activate Frontend
Frontend -> Backend: Envia transferência de moedas
activate Backend

Backend -> DB: Atualiza saldo do aluno
activate DB
DB --> Backend: Confirma atualização
deactivate DB
activate Email
Backend --> Email: Envia email para aluno
activate Aluno
Email --> Aluno: Recebe email com novo saldo
deactivate Email
deactivate Aluno
Backend --> Frontend: Operação concluída
deactivate Backend
Frontend --> Professor: Exibe confirmação
deactivate Frontend

@enduml