services:

  postgres:
    image: postgres:17
    container_name: postgres-db
    restart: unless-stopped
    env_file:
      - ../db/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../db/init:/docker-entrypoint-initdb.d
    networks:
      - backend-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: app
      RABBITMQ_DEFAULT_PASS: strong_password_here
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - backend-net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: springboot-backend
    restart: unless-stopped
    env_file:
      - ../backend/.env
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - backend-net

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.prod
    container_name: caddy-frontend
    restart: unless-stopped
    ports:
      - "80:80"
      # quando for HTTPS:
      # - "443:443"
    depends_on:
      - backend
    networks:
      - backend-net

volumes:
  postgres-data:
    driver: local
  rabbitmq-data:
    driver: local

networks:
  backend-net:
    driver: bridge