FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

EXPOSE 5173

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

USER appuser

CMD ["npm", "run", "dev", "--", "--host"]