spring.application.name=backend
server.port=${PORT:8080}

# Configuracoes de banco de dados
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JPA / Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false


# Definicao de profile ativo, modo dev (modo producao ativado via action) desativado pois o docker lida com isso com maior eficiencia
#spring.profiles.active=dev
# Prefixo de endpoint para padronizacao
spring.mvc.servlet.path=/api

# JWT
jwt.secret=${JWT_SECRET:2abd88b37704ecf84f2457d64a25c60e}
jwt.cookie-name=jwt
jwt.refresh-cookie-name=refresh
cookie.secure=true


# Multipart / upload de arquivos
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Desativar endpoints de desenvolvimento em modo de producao
#springdoc.api-docs.enabled=false
#springdoc.swagger-ui.enabled=false


# RabbitMQ
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=app
spring.rabbitmq.password=DXuuT5bLZLupYK3jBW0


# tomcat
server.tomcat.max-http-form-post-size=20MB
server.tomcat.max-swallow-size=20MB


app.security.csp.connect-src='self',${CSP_CONNECT_SRC:}
app.security.csp.style-src='self','unsafe-inline',${CSP_STYLE_SRC:}
app.security.csp.font-src='self',${CSP_FONT_SRC:}

# Email
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

mail.from=${MAIL_FROM}
app.url=${APP_URL}