spring.application.name=backend
server.port=${PORT:8080}

# Configuracoes de banco de dados
spring.datasource.url=${DB_URL:jdbc:mysql://host.docker.internal:3306/pontocerto}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false


# Definicao de profile ativo, modo dev (modo producao ativado via action) desativado pois o docker lida com isso com maior eficiencia
#spring.profiles.active=dev
# Prefixo de endpoint para padronizacao
spring.mvc.servlet.path=/api

# JWT
jwt.secret=${JWT_SECRET:2abd88b37704ecf84f2457d64a25c60e}
jwt.cookie-name=jwt
jwt.refresh-cookie-name=refresh
cookie.secure=true


# Multipart / upload de arquivos
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=15MB

# Desativar endpoints de desenvolvimento em modo de producao
#springdoc.api-docs.enabled=false
#springdoc.swagger-ui.enabled=false


# RabbitMQ
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=app
spring.rabbitmq.password=app123


# tomcat
server.tomcat.max-http-form-post-size=20MB
server.tomcat.max-swallow-size=20MB